apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ut690qz8n-dotnet-basic
  janus-idp.io/tekton: ut690qz8n-dotnet-basic
  backstage.io/kubernetes-id: ut690qz8n-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ut690qz8n-dotnet-basic
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
